In [7]:
print("Hello World")

Hello World


In [8]:
!pip3 install numpy

## Learning Numpy

#### New Headline

```
If not working on anaconda
then directly
pip3 install jupyterlab
```

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2,3],
                [4,2,5]])

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.ndim

2

In [13]:
arr.shape

(2, 3)

In [14]:
a = np.array([[1,2,4],[5,8,7]],dtype='float')
print(a)

[[1. 2. 4.]
 [5. 8. 7.]]


In [15]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [18]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [19]:
#from 0 to 5 get series of 10 number
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
narr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
narr = narr.reshape(4,3)
narr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
narr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
narr[1:,:3:2]

array([[ 4,  6],
       [ 7,  9],
       [10, 12]])

In [23]:
print("Hello World")

Hello World
